### ISSUE TITLE
Can't change the name of "Activities + Sports/Drama"

### ISSUE THREAD

**Issue by Seankuwamoto** [lukajaa/bay-clock-2#4]
The name of the "Activities + Sports/Drama" section is unable to be changed. If you were playing a sport, you might want to be able to change it to the name of that sport.

**Comment by lucaskchang** [comment]
Will work on it!
In the mean time, here is a short guide on how to change the names yourself:
Right click on the activities progress bar and click inspect element! 😀
Find the text Between the > and < and double click until you have highlighted it 💪
Delete the text and replace it with the name of your activity 🐶

⚠️You have to do this every time you reload! So make sure not to reload!!!⚠️

Have a nice day

CEO, COO, CFO, Lucas Chang

**Comment by lucaskchang** [comment]
Fixed
