### ISSUE TITLE
Activity start and end times are in 24 hour time.

### ISSUE THREAD

**Issue by Seankuwamoto** [lukajaa/bay-clock-2#5]
# Activity start and end times are in 24 hour time.

Activity start and end times are displayed in 24 hour time. Considering that in America 12 hour time is widely used, and that Bayclock runs on 12 hour time, I think it would make more sense for it to be displayed in 12 hour time. See attached screenshot below.
<img width="577" alt="Screen Shot 2023-02-16 at 10 14 23 AM" src="https://user-images.githubusercontent.com/56642599/219452442-bae13099-2a8d-4f21-a048-f2eba46020e3.png">

**Comment by lucaskchang** [comment]
Bro

**Comment by lucaskchang** [comment]
Not gonna fix
