### ISSUE TITLE
Lunch menu not zoomable.

### ISSUE THREAD

**Issue by Seankuwamoto** [lukajaa/bay-clock-2#7]
The lunch menu contains quite small writing, and previously it was possible to zoom into the lunch menu by pinching, however I have noticed now that it no longer is.

**Comment by lucaskchang** [comment]
Good observation! Feel free to submit a pull request if this topic is really bugging you. In the meantime, I recommend getting glasses and learning how to move your head closer to the computer screen.

**Comment by lucaskchang** [comment]
No PR. No response. Going to close
